/* =====================================================================
   TAEKWONDO JOURNEY — SERVICE WORKER
   Caches the whole app so the game keeps working inside a gym with no
   signal: the app shell (HTML/CSS/JS/manifest), every image, and the
   tutorial / warm-up videos are stored on the first online visit.

   v21: file lists are now generated by tools/update-sw.py (they had drifted:
        14 precached files no longer existed and games-arena.js /
        dashboard.js were missing, so an offline install was incomplete).
        Adds games-arena-2.js and the new warm-up clip torso_twist.mp4.

   v19: Naeryeo Chagi's Action Challenge ("Gravity Drop Challenge") redone.
        The old widget was an abstract side-panel bar with a "Full height"
        label crammed above a heavily rounded track — you dragged a handle
        up and down, and the character itself never moved. Replaced with a
        direct drag-on-the-fighter interaction: the player swipes on the
        character's own photo, and it live-crossfades between real ready /
        rise / drop poses as they drag, tracking their finger in real time,
        with a slim gauge and a bouncing directional hint instead of the old
        bar. Added a dedicated narochagi_live/ asset set (5 boy + 5 girl
        frames, rescaled and re-anchored onto one shared canvas so the
        crossfade reads as one figure moving, not two different-sized
        photos overlapping) — the original narochagi/ frames used elsewhere
        in the app are untouched. Scoring is unchanged; only the interaction
        and its presentation were replaced. Ap Chagi and Bakchagi3's Action
        Challenge widgets are unchanged.
   v18: Error Hunt redone properly. All 4 levels (head / knee / lean / heel)
        now use a purpose-made picture, warped from the SAME "Kick Extension"
        photo of the player's own character, with exactly the flaw the level
        is about and nothing else changed: head tipped down and eyes off the
        target, the kicking knee bent instead of snapped straight, the torso
        leaning back off the hips, and the standing heel lifted off the
        floor. Body parts are bent smoothly around their real joint (neck,
        knee, hip, ball of the foot) so there are no seams or warped limbs,
        and every tap zone (head / torso / kicking leg / standing foot) was
        recomputed to follow the new pose exactly. Replaces the v16/v17
        pictures, which reused existing action poses that didn't actually
        show their level's mistake (the "lean" picture, for one, was
        pixel-for-pixel identical in pose to "knee"; v17's fix only patched
        that one level by leaning the "knee" picture back, still reusing an
        existing pose rather than a real mistake picture).
   v16: Error Hunt now shows the SAME boy/girl characters used everywhere
        else in the game (Ready Stance / Chamber / Recoil / Kick Extension)
        instead of separate flat placeholder art, with the tappable zones
        re-mapped by hand onto each real photo. Also fixed one of those real
        assets (girl "Kick Extension") that had always had a solid black
        background baked in instead of a transparent one.
   v15: fixed a broken Error Hunt art asset — the standing leg was missing
        entirely from all 8 character pictures (boy/girl × 4 levels), so the
        standing foot appeared to float disconnected below the body. Added
        a properly connecting leg polygon (same technique used to generate
        the art originally) and regenerated all 8 images.
   v14: all 12 background pieces now also appear inside the game/menu cards
        themselves (not just full-page), belt system switched from 4 colors
        to a single white belt that gains 1-3 stripes, added a full
        competitive layer (username registration, per-attempt score log,
        personal + global leaderboard, CSV export), retry is no longer
        punished — only 3-in-a-row severe fails (<40%) send a player back
        to Learning — and the character sprite engine now cross-fades
        between frames with a subtle scale/lift instead of popping straight
        from one image to the next, for noticeably smoother motion.
   v13: warm-up rebuilt — same 8 filmed clips, same order, no repeats, 10s
        each, identical across all three kicks (was 5 exercises/skill at
        20s, with one clip reused/mirrored and 2 clips never played at all).
        Every screen now gets its own background image instead of silently
        falling back to the home-screen art (10 pieces of background art
        were sitting unused because of a screen-id lookup mismatch).
   v12: fixed the real cause of "images/videos not showing" — every asset on
        disk was actually .png/.jpg while the code asked for .webp (hidden by
        Windows Explorer's "hide known extensions"). All images converted to
        real .webp at the same filenames, IMAGE_FILES/VIDEO_FILES regenerated
        to match what's really on disk, and manifest.json + the two app icons
        (previously missing entirely) were added to the app shell.
   v11: removed a needless crossOrigin on the sprite preloader (game.js) that
        logged CORS errors and could interfere with character-animation
        preloading when the app is opened as a local file, not through a server.
   v10: adds the Quiz Blast game (code + markup + styles only, no new asset files).
   v9: axe-kick (boy) rise / drop / recoil frames redone on one shared canvas.
   v8: corrected kick-phase pictures (axe kick rise/drop/recoil, side-kick chamber/return), watermark-free images.
   v7: Error Hunt now uses the boy / girl character pictures (assets/images/error_hunt/).
   v6: adds the Action Challenge game (code + markup only, no new asset files).
   v5: adds the Error Hunt game (code + markup only, no new asset files).

   v4 changes:
   - Every image and video is now PRECACHED. Before, images were only cached
     when first seen, so a screen the player hadn't opened yet was blank
     offline, and videos were never cached at all (the worker skipped them).
   - Videos work offline: browsers play <video> with Range requests, which
     the worker used to hand straight to the network. Range requests are now
     answered from the cache (206 Partial Content) when the file is stored.
   - Navigations wait at most NAV_TIMEOUT_MS for the network before falling
     back to the cached shell, so a gym wifi that is "connected" but dead
     doesn't leave the app hanging on the loading screen.
   - Assets live in their own cache that is never trimmed (only the runtime
     cache for unknown files is), and CACHE_VERSION was bumped because the
     images are now .webp (game.js references changed).
   - IMAGE_FILES / VIDEO_FILES must list every file in assets/ — regenerate
     them (and bump CACHE_VERSION) whenever assets or code change.

   v3 (kept):
   - HTML navigations are network-first → players get updates as soon as
     they're online, and still fall back to the cached shell offline.
   - Fonts, Font Awesome and Three.js come from CDNs and are cached with
     stale-while-revalidate (including opaque responses).
   - A miss while offline returns Response.error() instead of `undefined`.
   - Our own JS/CSS use stale-while-revalidate too, so code updates arrive.
   ===================================================================== */

const CACHE_VERSION = 'tkd-v37';
const APP_SHELL_CACHE = `${CACHE_VERSION}-shell`;
const ASSET_CACHE = `${CACHE_VERSION}-assets`;     // precached images + videos, never trimmed
const RUNTIME_CACHE = `${CACHE_VERSION}-runtime`;  // anything else same-origin, trimmed
const CDN_CACHE = `${CACHE_VERSION}-cdn`;
const RUNTIME_MAX_ENTRIES = 250;
const NAV_TIMEOUT_MS = 4000;

const APP_SHELL_FILES = [
  './',
  './index.html',
  './style.css',
  './js/core/sprite-engine.js',
  './js/core/config.js',
  './js/data/curriculum.js',
  './js/core/helpers.js',
  './js/core/state.js',
  './js/core/screens.js',
  './js/learn/learning.js',
  './js/games/form-control.js',
  './js/games/puzzle.js',
  './js/games/performance.js',
  './js/games/action.js',
  './js/games/error-hunt.js',
  './js/games/quiz-blast.js',
  './js/games/quiz.js',
  './js/ui/winner.js',
  './js/ui/trophy-room.js',
  './js/ui/cooldown.js',
  './js/core/players.js',
  './js/ui/report.js',
  './js/ui/skill-menu.js',
  './js/learn/warmup.js',
  './js/app/main.js',
  './js/ui/certificate.js',
  './js/ui/effects.js',
  './js/games/arena-engine.js',
  './js/games/arena-games-2.js',
  './js/anim/skeleton.js',
  './js/anim/rig-views.js',
  './js/ui/dashboard.js',
  './js/lib/qr.js',
  './js/social/competition.js',
  './js/social/versus.js',
  './js/social/profile.js',
  './js/learn/curriculum-screen.js',
  './js/learn/review.js',
  './js/ui/journey.js',
  './js/ui/tabbar.js',
  './js/audio/audio.js',
  './js/audio/voice-record.js',
  './js/ui/read-aloud.js',
  './js/ui/shop.js',
  './js/ui/mission.js',
  './assets/icons/icons.css',
  './manifest.json',
  './assets/icons/icon-192.png',
  './assets/icons/icon-512.png',
  './assets/icons/icon-maskable-192.png',
  './assets/icons/icon-maskable-512.png',
  './privacy.html',
  './assets/anim/boy/boy.atlas',
  './assets/anim/boy/boy.json',
  './assets/anim/boy/boy.webp',
  './assets/anim/girl/girl.atlas',
  './assets/anim/girl/girl.json',
  './assets/anim/girl/girl.webp',
  './assets/audio/music/arena.mp3',
  './assets/audio/music/dojo.mp3',
  './assets/audio/sfx/bag-thud.mp3',
  './assets/audio/sfx/board-crack.mp3',
  './assets/audio/sfx/clap.mp3',
  './assets/audio/sfx/error.mp3',
  './assets/audio/sfx/gong.mp3',
  './assets/audio/sfx/hit-1.mp3',
  './assets/audio/sfx/hit-2.mp3',
  './assets/audio/sfx/hit-3.mp3',
  './assets/audio/sfx/hit-heavy.mp3',
  './assets/audio/sfx/rim.mp3',
  './assets/audio/sfx/star.mp3',
  './assets/audio/sfx/success.mp3',
  './assets/audio/sfx/taiko.mp3',
  './assets/audio/sfx/tick.mp3',
  './assets/audio/sfx/ui-click.mp3',
  './assets/audio/sfx/ui-pop.mp3',
  './assets/audio/sfx/whoosh-1.mp3',
  './assets/audio/sfx/whoosh-2.mp3',
  './assets/audio/sfx/whoosh-3.mp3',
  './assets/audio/sfx/win.mp3',
  './assets/audio/voice/manifest.json'
];

const IMAGE_FILES = [
  './assets/images/backgrounds/arena_bg.webp',
  './assets/images/backgrounds/basic_techniques_bg.webp',
  './assets/images/backgrounds/belt_training_bg.webp',
  './assets/images/backgrounds/dojo_interior_bg.webp',
  './assets/images/backgrounds/forms_practice_bg.webp',
  './assets/images/backgrounds/main_menu_bg.webp',
  './assets/images/backgrounds/memory_dojo_bg.webp',
  './assets/images/backgrounds/puzzle_challenge_bg.webp',
  './assets/images/backgrounds/quiz_room_bg.webp',
  './assets/images/backgrounds/reflex_arena_bg.webp',
  './assets/images/backgrounds/sparring_training_bg.webp',
  './assets/images/backgrounds/technique_quiz_bg.webp',
  './assets/images/characters/boy_char/apchagi/chamber_boy.webp',
  './assets/images/characters/boy_char/apchagi/extension_boy.webp',
  './assets/images/characters/boy_char/apchagi/ready_boy.webp',
  './assets/images/characters/boy_char/apchagi/recoil_boy.webp',
  './assets/images/characters/boy_char/apchagi/return_boy.webp',
  './assets/images/characters/boy_char/bikchagi/chamber_boy.webp',
  './assets/images/characters/boy_char/bikchagi/extension_boy.webp',
  './assets/images/characters/boy_char/bikchagi/ready_boy.webp',
  './assets/images/characters/boy_char/bikchagi/recoil_boy.webp',
  './assets/images/characters/boy_char/bikchagi/return_boy.webp',
  './assets/images/characters/boy_char/boy_hit_1.webp',
  './assets/images/characters/boy_char/boy_hit_2.webp',
  './assets/images/characters/boy_char/boy_hit_3.webp',
  './assets/images/characters/boy_char/boy_idle.webp',
  './assets/images/characters/boy_char/boy_walk_1.webp',
  './assets/images/characters/boy_char/boy_walk_2.webp',
  './assets/images/characters/boy_char/boy_walk_3.webp',
  './assets/images/characters/boy_char/boy_walk_4.webp',
  './assets/images/characters/boy_char/boy_walk_5.webp',
  './assets/images/characters/boy_char/boy_walk_6.webp',
  './assets/images/characters/boy_char/boy_win_1.webp',
  './assets/images/characters/boy_char/boy_win_2.webp',
  './assets/images/characters/boy_char/narochagi/drop_boy.webp',
  './assets/images/characters/boy_char/narochagi/ready_boy.webp',
  './assets/images/characters/boy_char/narochagi/recoil_boy.webp',
  './assets/images/characters/boy_char/narochagi/return_boy.webp',
  './assets/images/characters/boy_char/narochagi/rise_boy.webp',
  './assets/images/characters/coach_yang/chamber_coach.webp',
  './assets/images/characters/coach_yang/coach_idle.webp',
  './assets/images/characters/coach_yang/extension_coach.webp',
  './assets/images/characters/coach_yang/ready_coach.webp',
  './assets/images/characters/coach_yang/recoil_coach.webp',
  './assets/images/characters/coach_yang/return_coach.webp',
  './assets/images/characters/girl_char/apchagi/chamber_girl.webp',
  './assets/images/characters/girl_char/apchagi/extension_girl.webp',
  './assets/images/characters/girl_char/apchagi/ready_girl.webp',
  './assets/images/characters/girl_char/apchagi/recoil_girl.webp',
  './assets/images/characters/girl_char/apchagi/return_girl.webp',
  './assets/images/characters/girl_char/bikchagi/chamber_girl.webp',
  './assets/images/characters/girl_char/bikchagi/extension_girl.webp',
  './assets/images/characters/girl_char/bikchagi/ready_girl.webp',
  './assets/images/characters/girl_char/bikchagi/recoil_girl.webp',
  './assets/images/characters/girl_char/bikchagi/return_girl.webp',
  './assets/images/characters/girl_char/girl_hit_1.webp',
  './assets/images/characters/girl_char/girl_hit_2.webp',
  './assets/images/characters/girl_char/girl_idle.webp',
  './assets/images/characters/girl_char/girl_walk_1.webp',
  './assets/images/characters/girl_char/girl_walk_2.webp',
  './assets/images/characters/girl_char/girl_win_1.webp',
  './assets/images/characters/girl_char/narochagi/drop_girl.webp',
  './assets/images/characters/girl_char/narochagi/ready_girl.webp',
  './assets/images/characters/girl_char/narochagi/recoil_girl.webp',
  './assets/images/characters/girl_char/narochagi/return_girl.webp',
  './assets/images/characters/girl_char/narochagi/rise_girl.webp',
  './assets/images/error_hunt/boy_head.webp',
  './assets/images/error_hunt/boy_heel.webp',
  './assets/images/error_hunt/boy_knee.webp',
  './assets/images/error_hunt/boy_lean.webp',
  './assets/images/error_hunt/girl_head.webp',
  './assets/images/error_hunt/girl_heel.webp',
  './assets/images/error_hunt/girl_knee.webp',
  './assets/images/error_hunt/girl_lean.webp'
];

const VIDEO_FILES = [
  './assets/videos/apchagi-tutorial.mp4',
  './assets/videos/bikchagi-tutorial.mp4',
  './assets/videos/naeryeochagi-tutorial.mp4',
  './assets/videos/warmup/double_leg_hamstring.mp4',
  './assets/videos/warmup/forward_lunge.mp4',
  './assets/videos/warmup/jumping_jacks.mp4',
  './assets/videos/warmup/lateral_lunge.mp4',
  './assets/videos/warmup/single_leg_hamstring.mp4',
  './assets/videos/warmup/straddle_fold.mp4',
  './assets/videos/warmup/straddle_side_reach.mp4'
];

const CDN_HOSTS = [
  'fonts.googleapis.com',
  'fonts.gstatic.com',
  'cdnjs.cloudflare.com'
];

// cache.addAll() is all-or-nothing: if ANY single file 404s, everything
// silently fails to cache. Cache each file independently instead.
function addOne(cache, file) {
  return cache.add(new Request(file, { cache: 'reload' })).catch((err) =>
    console.warn(`SW install: failed to cache ${file}`, err)
  );
}

// Videos are big (~16 MB in total), so they are fetched one at a time and
// skipped when already stored. Safe to call repeatedly; concurrent calls share
// one run. Any file that fails (connection dropped) is retried next time.
let videoPrecacheRun = null;
function precacheVideos() {
  if (!videoPrecacheRun) {
    videoPrecacheRun = (async () => {
      const cache = await caches.open(ASSET_CACHE);
      for (const file of VIDEO_FILES) {
        const url = new Request(file).url;
        if (await cache.match(url)) continue;
        await addOne(cache, file);
      }
    })().finally(() => { videoPrecacheRun = null; });
  }
  return videoPrecacheRun;
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const shell = await caches.open(APP_SHELL_CACHE);
    const assets = await caches.open(ASSET_CACHE);
    await Promise.all([
      ...APP_SHELL_FILES.map((file) => addOne(shell, file)),
      ...IMAGE_FILES.map((file) => addOne(assets, file))
    ]);
  })());
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  const keep = [APP_SHELL_CACHE, ASSET_CACHE, RUNTIME_CACHE, CDN_CACHE];
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((key) => key.startsWith('tkd-') && !keep.includes(key))
            .map((key) => caches.delete(key))
      ))
      .then(() => self.clients.claim())
      // Started after activation and NOT awaited, so the big video download
      // never holds up page loads. Navigations re-trigger it (see networkFirst).
      .then(() => { precacheVideos().catch(() => {}); })
  );
});

async function trimCache(cacheName, maxEntries) {
  const cache = await caches.open(cacheName);
  const keys = await cache.keys();
  // Cache Storage keeps insertion order, so the oldest entries come first.
  for (let i = 0; i < keys.length - maxEntries; i++) await cache.delete(keys[i]);
}

// HTML: try the network (fresh version); fall back to the cached shell when
// offline OR when the network takes longer than NAV_TIMEOUT_MS to answer.
async function networkFirst(event, req) {
  const cache = await caches.open(APP_SHELL_CACHE);
  const fallback = async () =>
    (await cache.match(req, { ignoreSearch: true })) ||
    (await cache.match('./index.html')) ||
    null;

  const network = fetch(req).then((response) => {
    if (response && response.ok) {
      const copy = response.clone();
      cache.put('./index.html', copy).catch(() => {});
    }
    return response;
  });

  const cached = await fallback();
  if (!cached) return network.catch(() => Response.error());   // first ever visit

  const timeout = new Promise((resolve) => setTimeout(() => resolve(null), NAV_TIMEOUT_MS));
  try {
    const winner = await Promise.race([network, timeout]);
    if (winner) {
      event.waitUntil(precacheVideos().catch(() => {}));       // online: top up any missing videos
      return winner;
    }
    event.waitUntil(network.catch(() => {}));                  // let the slow request still refresh the cache
    return cached;
  } catch (err) {
    return cached;
  }
}

// CDN assets + our own JS/CSS: answer instantly from cache, refresh in the
// background — so an update to game.js/style.css reaches players on their
// next visit instead of being stuck behind cache-first forever.
async function staleWhileRevalidate(event, req, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(req, { ignoreSearch: cacheName === APP_SHELL_CACHE });
  const network = fetch(req)
    .then((response) => {
      // type 'opaque' (status 0) is accepted too, for links without crossorigin.
      if (response && (response.ok || response.type === 'opaque')) {
        cache.put(req, response.clone());
      }
      return response;
    })
    .catch(() => null);
  if (cached) {
    event.waitUntil(network);
    return cached;
  }
  return (await network) || Response.error();
}

// Videos: serve from the cache whenever the file is stored — including the
// Range requests <video> makes for playback and seeking (answered as 206).
// Not stored yet → let the network handle it untouched.
async function serveVideo(req) {
  const cache = await caches.open(ASSET_CACHE);
  const cached = await cache.match(req.url);   // match by URL only (ignores the Range header)
  if (!cached) {
    try { return await fetch(req); } catch (err) { return Response.error(); }
  }
  const rangeHeader = req.headers.get('range');
  if (!rangeHeader) return cached;

  const m = /^bytes=(\d*)-(\d*)$/.exec(rangeHeader.trim());
  if (!m || (m[1] === '' && m[2] === '')) return cached;
  const blob = await cached.blob();
  const size = blob.size;
  let start, end;
  if (m[1] === '') {                        // "bytes=-N" → the last N bytes
    start = Math.max(0, size - parseInt(m[2], 10));
    end = size - 1;
  } else {
    start = parseInt(m[1], 10);
    end = m[2] === '' ? size - 1 : Math.min(parseInt(m[2], 10), size - 1);
  }
  if (start >= size || start > end) {
    return new Response(null, { status: 416, headers: { 'Content-Range': `bytes */${size}` } });
  }
  return new Response(blob.slice(start, end + 1), {
    status: 206,
    statusText: 'Partial Content',
    headers: {
      'Content-Type': cached.headers.get('Content-Type') || 'video/mp4',
      'Content-Range': `bytes ${start}-${end}/${size}`,
      'Content-Length': String(end - start + 1),
      'Accept-Ranges': 'bytes'
    }
  });
}

// Same-origin images and other media: cache-first, fill cache at runtime.
async function cacheFirst(event, req) {
  const cached = await caches.match(req);
  if (cached) return cached;
  try {
    const response = await fetch(req);
    // Only cache complete, successful same-origin responses.
    if (response && response.status === 200 && response.type === 'basic') {
      const copy = response.clone();
      event.waitUntil(
        caches.open(RUNTIME_CACHE)
          .then((cache) => cache.put(req, copy))
          .then(() => trimCache(RUNTIME_CACHE, RUNTIME_MAX_ENTRIES))
      );
    }
    return response;
  } catch (err) {
    return Response.error();
  }
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  const isVideoAsset = req.destination === 'video' || /\.(mp4|webm|mov|m4v)$/i.test(url.pathname);

  if (url.origin === self.location.origin && isVideoAsset) {
    event.respondWith(serveVideo(req));
    return;
  }

  // Any other Range request: let the browser handle it directly.
  if (req.headers.has('range')) return;

  if (req.mode === 'navigate') {
    event.respondWith(networkFirst(event, req));
    return;
  }

  if (CDN_HOSTS.includes(url.hostname)) {
    event.respondWith(staleWhileRevalidate(event, req, CDN_CACHE));
    return;
  }

  if (url.origin !== self.location.origin) return; // other cross-origin: don't touch

  if (/\.(js|css|json)$/i.test(url.pathname)) {
    event.respondWith(staleWhileRevalidate(event, req, APP_SHELL_CACHE));
    return;
  }

  event.respondWith(cacheFirst(event, req));
});